#!/usr/bin/env python3
"""Regenerate the paper's data tables (LaTeX) from the model / results.

Usage:
    python make_tables.py --input results/main.json --out ../Paper/Section/_generated

Writes:
    tab_breakeven.tex   break-even extractable value V* = (F+1)q(s+R)+Cop
    tab_summary.tex      one-line key scalars (psucc floor, PoC, thresholds)

These files are \\input by the paper so the numbers can never drift from the
artifact: re-running the pipeline rewrites them.
"""
from __future__ import annotations

import argparse
import json
import os

from shardbribe import model


def breakeven_table(Ns, qs, s, R, Cop) -> str:
    lines = [
        "% AUTO-GENERATED by artifact/make_tables.py -- do not edit by hand.",
        "\\begin{tabular}{@{}lcccc@{}}",
        "\\toprule",
        "$N$ ($k{=}F{+}1$) & $q{=}0.25$ & $q{=}0.5$ & $q{=}0.75$ & $q{=}1.0$ \\\\",
        "\\midrule",
    ]
    for N in Ns:
        k = model.equivocation_floor(N)
        vals = [model.breakeven_value(N, q, s=s, R=R, Cop=Cop) for q in qs]
        cells = " & ".join(f"{v:.2f}" for v in vals)
        lines.append(f"${N}$ (${k}$) & {cells} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


_WINDOW_TEX = {"gated": "\\gated", "open": "\\openg", "depends": "\\dependsg"}


def realsystems_table(res) -> str:
    """RQ7 documented-parameter case study: one row per named system, the two
    gates split into a colored Window (G1) state and a $V^{*}$ (G2) cost, and a
    one-word colored verdict (\\immune / \\hardgate / \\exposed) instead of the
    old prose blob. The verdict macros are defined in the paper preamble."""
    rows = res["rq7"]["rows"]
    out = [
        "% AUTO-GENERATED by artifact/make_tables.py -- do not edit by hand.",
        "\\begin{tabular}{@{}l c r r r r c c@{}}",
        "\\toprule",
        "System & Sharded & $N$ & Unbond. & $q$ & $V^{*}$ & Window (G1) & "
        "Verdict \\\\",
        "\\midrule",
    ]
    for r in rows:
        sh = "yes" if r["sharded"] else "no"
        ub = f"{r['unbonding_days']:.0f}\\,d" if r["unbonding_days"] > 0 else "--"
        q = f"{r['q_est']:.2f}"
        bev = f"{r['breakeven_V_stakes']:.0f}"
        win = _WINDOW_TEX.get(r["window"], r["window"])
        if r["window"] == "gated":
            verdict = "\\immune"
        elif r["q_est"] > 0.99:
            verdict = "\\hardgate"
        else:
            verdict = "\\exposed"
        out.append(f"{r['name']} & {sh} & {r['N']} & {ub} & {q} & ${bev}$ & "
                   f"{win} & {verdict} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


def defenses_table(res) -> str:
    """RQ5 defensive levers as a table (companion to fig_defenses): which gate
    each lever attacks, the resulting $\\pwin$, bribe $B$, expected profit, and
    whether it drives the attack unprofitable. Numbers come straight from the
    artifact so they cannot drift from Fig.~\\ref{fig:defenses}."""
    rq5 = res["rq5"]
    # short single-column-friendly labels (the long run_all names overflow a
    # \columnwidth float); the caption carries the gloss.
    short = {
        "baseline": "None (baseline)",
        "Finality-gated receipts": "Finality-gating",
        "Persistent slashability": "Persistent slash.",
        "Fast evidence (lower Tacc)": "Fast evidence",
        "Larger committee": "Larger committee",
    }
    out = [
        "% AUTO-GENERATED by artifact/make_tables.py -- do not edit by hand.",
        "\\begin{tabular}{@{}l c r r r c@{}}",
        "\\toprule",
        "Defensive lever & Gate & $\\pwin$ & $B$ & $\\mathbb{E}[\\Pi]$ & "
        "Closes? \\\\",
        "\\midrule",
    ]
    for r in rq5["rows"]:
        aff = r["affects"]
        g1 = "pwin" in aff
        g2 = ("q" in aff) or ("B" in aff)
        if aff.strip() == "--":
            gate = "--"
        elif g1 and g2:
            gate = "G1+G2"
        elif g1:
            gate = "G1"
        else:
            gate = "G2"
        lever = short.get(r["defense"], r["defense"]).replace("Tacc", "$\\Tacc$")
        closes = "\\yes" if r["profit"] <= 0 else "\\nomark"
        out.append(f"{lever} & {gate} & {r['pwin']:.2f} & "
                   f"{r['B']:.2f} & {r['profit']:+.1f} & {closes} \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


_VERDICT_TEX = {"OPEN": "\\openwin", "RULED_OUT": "\\ruledout",
                "INDETERMINATE": "\\indet"}


def _lat_ms(ms):
    """Human-readable latency from milliseconds: keeps sub-minute values in
    seconds and promotes larger ones to min/h/d so a 11.5 s floor and a ~26 d
    late-enforcement tail are both legible (and never read as raw seconds)."""
    if ms is None:
        return None
    s = ms / 1000.0
    if s < 90:
        return f"{s:.1f}\\,s"
    m = s / 60.0
    if m < 90:
        return f"{m:.1f}\\,min"
    h = m / 60.0
    if h < 48:
        return f"{h:.1f}\\,h"
    return f"{h/24.0:.1f}\\,d"


def _verdict_tex(v) -> str:
    return _VERDICT_TEX.get(v, "\\textsc{[pending]}")


def _provenance_macros(paths) -> dict:
    r"""RQ8 rehearsal-vs-real-client-code wording, generated from the DATA so the
    prose can never claim more than was measured. The fast-exit positive control
    flips to "real client code" once results/measured/fastexit-devnet-positive-rpc
    .jsonl has records (localnet/run_arm.sh C); the paired race once
    across-v3-selffill-rpc.jsonl does. Until then the macros stay at their
    in-process-\texttt{shadow} rehearsal wording. The section reads these via
    \ArtifactPosCtrlMode / \ArtifactPairedMode / \ArtifactRqEightProvenance /
    \ArtifactRqEightOwed / \ArtifactRqEightRemains / \ArtifactRowProvenance."""
    paths = paths or {}

    def has_records(stem):
        p = paths.get(stem) or {}
        q = p.get("q") or {}; pw = p.get("p_win") or {}
        ts = p.get("T_settle_fit") or {}; ta = p.get("T_acc_fit") or {}
        return bool(p) and bool(q.get("n") or pw.get("n")
                                or ts.get("empirical_quantiles")
                                or ta.get("empirical_quantiles"))

    pos = has_records("fastexit-devnet-positive-rpc")
    paired = has_records("across-v3-selffill-rpc")
    # Flip the positive control to the arm-C "observed unbonding completion" wording
    # only when the records actually carry it (a real MsgUndelegate whose maturity was
    # read on-chain), not merely because the file exists.
    pos_unbond = pos and bool(
        (paths.get("fastexit-devnet-positive-rpc") or {}).get("unbond_observed"))
    pos_real = ("real consensus client code (observed unbonding completion)"
                if pos_unbond else "real consensus client code")

    if pos_unbond:
        pos_mode = ("the fast-exit positive control runs on real client code (observed unbonding "
                    "completion): the equivocator submits a real \\texttt{MsgUndelegate} whose "
                    "maturity is read on-chain against the slash, on a two-nodes-one-key localnet")
    elif pos:
        pos_mode = ("the fast-exit positive control runs on real client code "
                    "(the \\texttt{rpc} backend on a two-nodes-one-key localnet)")
    else:
        pos_mode = "the fast-exit positive control is an in-process \\texttt{shadow} rehearsal"
    paired_mode = ("the paired race runs on real client code" if paired else
                   "the paired race is an in-process \\texttt{shadow} rehearsal")

    if pos and paired:
        prov = ("the paired race and the fast-exit positive control now run on real "
                "consensus client code"
                + (" (the latter via observed unbonding completion)" if pos_unbond else ""))
    elif pos:
        prov = ("the paired race remains a \\emph{rehearsal} on the validated model (the "
                "fast-exit positive control now runs on " + pos_real + "), "
                "\\emph{not} yet a production paired run")
    elif paired:
        prov = ("the fast-exit positive control remains a \\emph{rehearsal} on the validated "
                "model (the paired race now runs on real consensus client code)")
    else:
        prov = ("the paired race and the fast-exit positive control are a \\emph{rehearsal} on "
                "the validated model, \\emph{not} a production run against real consensus "
                "client code")

    base_owed = ("the $\\ge 4$-node propagation timing, and a self-run-archive "
                 "re-derivation of $q_{\\max}$")
    owed = base_owed if (pos and paired) else (
        "the real-client-code re-derivation (the \\texttt{rpc} backend on a private "
        "two-nodes-one-key localnet), " + base_owed)

    remains = ("to complete the remaining propagation-timing and self-run-archive re-derivations"
               if paired else
               "to replace the in-process rehearsal of the paired race with the "
               "real-client-code localnet run")

    if pos and paired:
        rowprov = ("the self-fill and fast-exit rows are the real-client-code runs of"
                   + (" (the fast-exit row via observed unbonding completion)" if pos_unbond
                      else ""))
    elif pos:
        rowprov = ("the self-fill row is the in-process rehearsal, and the fast-exit row the "
                   "real-client-code run"
                   + (" (observed unbonding completion)" if pos_unbond else "") + ", of")
    elif paired:
        rowprov = ("the fast-exit row is the in-process rehearsal, and the self-fill row the "
                   "real-client-code run, of")
    else:
        rowprov = "the self-fill and fast-exit rows are the in-process rehearsal of"

    return {"ArtifactPosCtrlMode": pos_mode, "ArtifactPairedMode": paired_mode,
            "ArtifactRqEightProvenance": prov, "ArtifactRqEightOwed": owed,
            "ArtifactRqEightRemains": remains, "ArtifactRowProvenance": rowprov}


def _measured_macros(res) -> dict:
    """RQ8 measured scalars; LaTeX [pending] placeholders until prereg/rq8-v1 is
    executed and results/measured/*.jsonl exists (run_all writes res['rq8'])."""
    pend = "\\,\\textit{[pending]}\\,"
    m = {"ArtifactQMaxCosmos": pend, "ArtifactQMaxCosmosCI": pend, "ArtifactQMaxN": pend,
         "ArtifactTaccCosmosLo": pend, "ArtifactTaccCosmosHi": pend,
         "ArtifactTsettleIBC": pend, "ArtifactCosmosVerdict": "\\textsc{[pending]}",
         "ArtifactBridgeTsettle": pend, "ArtifactBridgePwin": pend,
         "ArtifactBridgeVerdict": "\\textsc{[pending]}", "ArtifactCliffCosmos": pend}
    m.update(_provenance_macros(None))         # default: in-process-rehearsal wording
    rq8 = res.get("rq8")
    if not (rq8 and rq8.get("status") == "ok"):
        return m
    paths = rq8.get("paths", {})
    m.update(_provenance_macros(paths))        # flip to real-client-code where the data exists

    def q_quant_s(fit, p):  # empirical quantile at p, human-readable latency
        return _lat_ms((fit or {}).get("empirical_quantiles", {}).get(str(p)))

    def q_med_s(fit):       # median empirical quantile, human-readable latency
        return q_quant_s(fit, 0.5)

    # q_max from the pooled CometBFT-family sample (stronger n) if present,
    # else the Hub path; the verdict + latencies come from the Hub safe target.
    qsrc = paths.get("cometbft-qmax-pool") or paths.get("cosmoshub-4")
    if qsrc:
        q = qsrc.get("q", {})
        if q.get("q_point_upper_bound") is not None:
            m["ArtifactQMaxCosmos"] = f"{q['q_point_upper_bound']:.2f}"
            lo, hi = (q.get("ci") or [None, None])[:2]
            if lo is not None:
                m["ArtifactQMaxCosmosCI"] = f"[{lo:.2f},\\,{hi:.2f}]"
        if q.get("n"):
            m["ArtifactQMaxN"] = str(q["n"])
        # Adversarial T_acc upper bound: the P90 of the REAL pooled enforcement
        # latency, which already contains the observed late-enforcement tail
        # (a single batch was enforced ~25 days late). This is the empirical
        # upper bound the structural RULED_OUT is stress-tested against; it is
        # real passive data, not a shadow number. The active evidence-suppression
        # experiment that would tighten it further remains future work (see text).
        if q_quant_s(qsrc.get("T_acc_fit"), 0.9):
            m["ArtifactTaccCosmosHi"] = q_quant_s(qsrc.get("T_acc_fit"), 0.9)
    cos = paths.get("cosmoshub-4")
    if cos:
        m["ArtifactCosmosVerdict"] = _verdict_tex(cos.get("verdict"))
        tstar = (cos.get("distance_to_cliff") or {}).get("T_star_settle")
        if tstar is not None:
            m["ArtifactCliffCosmos"] = _lat_ms(tstar)
        if q_med_s(cos.get("T_acc_fit")):
            m["ArtifactTaccCosmosLo"] = q_med_s(cos.get("T_acc_fit"))
    # Native-IBC T_settle is the negative-control arm. Realised on a real public
    # IBC channel (Cosmos Hub -> Osmosis, collect_ibc_public.py); the self-run
    # two-zone devnet (collect_ibc.py) remains an accepted alternative source.
    ibc = paths.get("ibc-cosmoshub-osmosis-negative") or paths.get("ibc-devnet-negative")
    if ibc and q_med_s(ibc.get("T_settle_fit")):
        m["ArtifactTsettleIBC"] = q_med_s(ibc.get("T_settle_fit"))
    # Bridge user-leg T_settle stays the PURE real-fills median (across-v3); the
    # paired p_win + OPEN verdict come from the devnet self-fill rehearsal kept in
    # a separate file (across-v3-selffill) so the real settlement data is never
    # mixed with rehearsal episodes.
    br = paths.get("across-v3")
    if br and q_med_s(br.get("T_settle_fit")):
        m["ArtifactBridgeTsettle"] = q_med_s(br.get("T_settle_fit"))
    # Prefer the REAL-client-code paired race (across-v3-selffill-rpc) over the
    # in-process shadow rehearsal (across-v3-selffill) for the OPEN verdict + p_win
    # whenever it exists -- same data-gated flip as the provenance wording above, so
    # the headline number never claims more than was actually run.
    sf = paths.get("across-v3-selffill-rpc") or paths.get("across-v3-selffill")
    if sf:
        m["ArtifactBridgeVerdict"] = _verdict_tex(sf.get("verdict"))
        pwd = sf.get("p_win") or {}
        if pwd.get("n"):                  # only show p_win if paired data exist
            m["ArtifactBridgePwin"] = f"{pwd['p_win']:.2f}"
    return m


def measured_table(res) -> str:
    """RQ8 per-path table; only written when rq8 results are present."""
    paths = res.get("rq8", {}).get("paths", {})
    out = [
        "% AUTO-GENERATED by artifact/make_tables.py -- do not edit by hand.",
        "\\begin{tabularx}{\\textwidth}{@{}lllrllX@{}}",
        "\\toprule",
        "System & Path & $n_{\\mathrm{obs}}$ & $\\hat q$ & $\\Tacc$ (med) & "
        "$\\Tsettle$ (med) & "
        "$\\pwin$ / verdict \\\\",
        "\\midrule",
    ]
    def esc(s):                       # escape LaTeX specials in config-derived text
        s = str(s)
        for ch in ("_", "&", "%", "#"):
            s = s.replace(ch, "\\" + ch)
        return s
    for stem, p in paths.items():
        q = p.get("q", {})
        qhat = (f"{q['q_point_upper_bound']:.2f}"
                if q.get("q_point_upper_bound") is not None else "N/A")
        ta = (p.get("T_acc_fit") or {}).get("empirical_quantiles", {}).get("0.5")
        ts = (p.get("T_settle_fit") or {}).get("empirical_quantiles", {}).get("0.5")
        ta_s = _lat_ms(ta) if ta is not None else "--"
        ts_s = _lat_ms(ts) if ts is not None else "--"
        n_pair = (p.get("p_win") or {}).get("n", 0)
        n = q.get("n") or n_pair or "--"          # measurement n (q-arm or paired)
        pw = (p.get("p_win") or {}).get("p_win")
        pw_s = f"{pw:.2f}, " if (pw is not None and n_pair) else ""
        out.append(
            f"{esc(p.get('system', stem))} & {esc(p.get('path',''))} & "
            f"{n} & {qhat} & {ta_s} & {ts_s} & "
            f"{pw_s}{_verdict_tex(p.get('verdict'))} \\\\")
    out += ["\\bottomrule", "\\end{tabularx}"]
    return "\n".join(out) + "\n"


def summary_macros(res) -> str:
    poc = res["validation"]["poc"]
    floor = res["floor"]
    # psucc floor at phi=0.5 for k=F+1 (first curve)
    import numpy as np
    phi = np.array(floor["phi"])
    i50 = int(np.argmin(np.abs(phi - 0.5)))
    psucc_floor = floor["curves"]["k=F+1"][i50]
    err = res["validation"]["max_abs_err"]
    rt = res.get("runtime_sec", 0.0)
    macros = {
        "ArtifactMaxValErr": f"{err:.3f}",
        "ArtifactPoCN": str(poc["N"]),
        "ArtifactPoCk": str(poc["k"]),
        "ArtifactPoCEvidence": str(poc["evidence_produced"]),
        "ArtifactPoCBribes": str(poc["bribes_paid"]),
        "ArtifactPsuccFloor": f"{psucc_floor:.2f}",
        "ArtifactRuntime": f"{rt:.0f}",
    }
    if "rq6" in res:
        tb = res["rq6"]
        macros["ArtifactSigBytes"] = str(tb["signature"]["sig_bytes"])
        macros["ArtifactEvidenceBytes"] = str(tb["signature"]["evidence_bytes"])
        macros["ArtifactTbBaseRho"] = f"{tb['baseline']['rho_measured']:.2f}"
        macros["ArtifactTbBasePwin"] = f"{tb['baseline']['pwin_measured']:.2f}"
        macros["ArtifactTbSettleMs"] = f"{tb['baseline']['mean_T_settle_ms']:.0f}"
        macros["ArtifactTbAccMs"] = f"{tb['baseline']['mean_T_acc_ms']:.0f}"
    macros.update(_measured_macros(res))   # RQ8 measured scalars (or [pending])
    out = ["% AUTO-GENERATED by artifact/make_tables.py -- do not edit by hand."]
    for k, v in macros.items():
        out.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default=os.path.join("results", "main.json"))
    ap.add_argument("--out", default=os.path.join("..", "Paper", "Section", "_generated"))
    args = ap.parse_args()
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, args.input), "r", encoding="utf-8") as fh:
        res = json.load(fh)
    outdir = os.path.join(here, args.out)
    os.makedirs(outdir, exist_ok=True)

    c = res["config"]["rq2"]
    Ns = [4, 7, 16, 31, 64, 100]
    qs = [0.25, 0.5, 0.75, 1.0]
    with open(os.path.join(outdir, "tab_breakeven.tex"), "w",
              encoding="utf-8") as fh:
        fh.write(breakeven_table(Ns, qs, c["s"], c["R"], Cop=1.0))
    with open(os.path.join(outdir, "tab_summary.tex"), "w",
              encoding="utf-8") as fh:
        fh.write(summary_macros(res))
    if "rq7" in res:
        with open(os.path.join(outdir, "tab_realsystems.tex"), "w",
                  encoding="utf-8") as fh:
            fh.write(realsystems_table(res))
    if "rq5" in res:
        with open(os.path.join(outdir, "tab_defenses.tex"), "w",
                  encoding="utf-8") as fh:
            fh.write(defenses_table(res))
    wrote_measured = ""
    if res.get("rq8", {}).get("status") == "ok" and res["rq8"].get("paths"):
        with open(os.path.join(outdir, "tab_measured.tex"), "w",
                  encoding="utf-8") as fh:
            fh.write(measured_table(res))
        wrote_measured = ", tab_measured.tex"
    print(f"[make_tables] wrote tab_breakeven.tex, tab_summary.tex, "
          f"tab_realsystems.tex, tab_defenses.tex{wrote_measured} to {outdir}")


if __name__ == "__main__":
    main()
